id: P0E808408
initial_creation_type: input
source_metadata:
  title: Orgyen Lingpa Series
  language: bo
  description: 'Texts by the famous treasure revealer Orgyen Lingpa (o rgyan gling
    pa, b. 1323):'
  volume:
    98a321c9cb8046ca8615951c6d1b09d8:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: History
created_at: '2022-03-01T01:07:17.413732'
last_modified_at: '2022-03-01T01:07:17.413735'
statistics:
  total_words: 3009
  total_non_words: 271
quality:
  non_words_ratio: 0.09
